/**
 * 一般企業（コーポレートサイト）向けセクション定義
 */
import type { SectionDef, StepDef } from "../../schema";

export const corporateSteps: StepDef[] = [
  { step: 1, title: "ステップ1", description: "まずはここから！会社の基本情報と理念を固めましょう" },
  { step: 2, title: "ステップ2", description: "深掘りタイム！ストーリーと詳細情報を聞かせてください" },
];

export const corporateSections: SectionDef[] = [
  {
    id: "tone-manner",
    title: "トーン&マナー",
    description: "Webサイトの文章ルールを最初に決めましょう！",
    icon: "🎨",
    step: 1,
    estimatedMinutes: 3,
    fields: [
      {
        name: "tone_settings",
        label: "文章のトーン&マナー設定",
        type: "tone-manner",
        hint: "ここで決めたルールがサイト全体の文章に統一感を持たせます！",
        dnaSheet: "31_Tone_And_Manner",
        dnaField: "brand_voice_summary",
        toneCategories: [
          { name: "文体", key: "文体", options: ["ですます調", "である調"] },
          { name: "トーンの温度感", key: "温度感", options: ["親しみやすい", "プロフェッショナル", "革新的", "落ち着いた", "力強い"] },
          { name: "主語", key: "主語", options: ["当社", "私たち", "弊社", "我々"] },
          { name: "お客様の呼び方", key: "顧客呼称", options: ["お客さま", "お客様", "クライアント", "パートナー"] },
        ],
      },
    ],
  },
  {
    id: "company-basic",
    title: "会社概要",
    description: "会社の基本情報をお願いします！",
    icon: "🏢",
    step: 1,
    estimatedMinutes: 5,
    fields: [
      { name: "company_name", label: "会社名（正式名称）", type: "text", placeholder: "例：株式会社〇〇", dnaSheet: "00_Company", dnaField: "company_name", required: true },
      { name: "established", label: "設立年月", type: "text", placeholder: "例：2010年4月", dnaSheet: "00_Company", dnaField: "established" },
      { name: "ceo_name", label: "代表者名", type: "text", placeholder: "例：山田 太郎", dnaSheet: "00_Company", dnaField: "ceo_name", required: true },
      { name: "address", label: "所在地", type: "text", placeholder: "例：東京都渋谷区〇〇1-2-3", dnaSheet: "00_Company", dnaField: "address" },
      { name: "phone", label: "電話番号", type: "tel", placeholder: "例：03-1234-5678", dnaSheet: "00_Company", dnaField: "phone" },
      { name: "company_url", label: "現在のWebサイトURL（あれば）", type: "url", placeholder: "例：https://example.com", dnaSheet: "00_Company", dnaField: "url" },
      { name: "employee_count", label: "従業員数", type: "text", placeholder: "例：50名", dnaSheet: "00_Company", dnaField: "employee_count" },
      { name: "capital", label: "資本金", type: "text", placeholder: "例：1,000万円", dnaSheet: "00_Company", dnaField: "capital" },
      {
        name: "business_description",
        label: "事業内容",
        type: "textarea",
        placeholder: "主な事業内容を教えてください",
        hint: "箇条書きでもOKです！",
        dnaSheet: "00_Company",
        dnaField: "business_description",
        rows: 5,
      },
      {
        name: "sns_accounts",
        label: "SNSアカウント",
        type: "sns",
        hint: "運用しているSNSがあれば教えてください！",
        dnaSheet: "00_Company",
        dnaField: "sns_accounts",
      },
    ],
  },
  {
    id: "ceo-profile",
    title: "代表メッセージ",
    description: "代表の方のプロフィールとメッセージをお願いします！",
    icon: "👤",
    step: 1,
    estimatedMinutes: 10,
    fields: [
      {
        name: "ceo_career",
        label: "代表の経歴",
        type: "textarea",
        placeholder: "例：\n〇〇大学卒業\n〇〇株式会社入社\n2010年 株式会社〇〇を設立",
        dnaSheet: "10_Staff",
        dnaField: "career_summary",
      },
      {
        name: "ceo_message",
        label: "代表メッセージ",
        type: "textarea",
        placeholder: "サイトに掲載する代表メッセージを教えてください。ラフに書いてもらえればAIで整えますよ！",
        hint: "HPに載せる代表メッセージです！ラフでOK！",
        dnaSheet: "00_Company",
        dnaField: "ceo_message",
        rows: 8,
        textSuggestions: [
          { label: "創業の想いから", text: "当社を設立したのは、" },
          { label: "お客様への約束", text: "私たちがお客さまにお約束すること。それは" },
          { label: "未来のビジョン", text: "私たちが目指す未来は、" },
        ],
      },
    ],
  },
  {
    id: "philosophy",
    title: "企業理念・ビジョン",
    description: "会社として大切にしていることを教えてください！",
    icon: "💡",
    step: 1,
    estimatedMinutes: 10,
    fields: [
      {
        name: "mission",
        label: "ミッション（使命）",
        type: "textarea",
        placeholder: "例：{{company_name}}は〇〇を通じて、社会に貢献します",
        hint: "「何のために存在する会社か」を教えてください！",
        dnaSheet: "03_Philosophy",
        dnaField: "mission",
        textSuggestions: [
          { label: "社会課題から", text: "私たちは、" },
          { label: "お客様視点で", text: "お客さまが" },
        ],
      },
      {
        name: "vision",
        label: "ビジョン（目指す姿）",
        type: "textarea",
        placeholder: "例：2030年までに〇〇の分野でNo.1になる",
        hint: "将来こうなりたいという理想の姿を教えてください！",
        dnaSheet: "03_Philosophy",
        dnaField: "vision",
      },
      {
        name: "values",
        label: "バリュー（行動指針・大切にしている価値観）",
        type: "repeater",
        placeholder: "例：誠実であること",
        hint: "社員に大切にしてほしい価値観を教えてください！",
        dnaSheet: "03_Philosophy",
        dnaField: "values",
        defaultCount: 3,
      },
      {
        name: "never_do",
        label: "絶対にやらないと決めていること",
        type: "textarea",
        placeholder: "例：品質を犠牲にしたコストダウンは絶対にしません",
        hint: "「やらないこと」は最強の差別化ポイントです！",
        dnaSheet: "03_Philosophy",
        dnaField: "never_do",
      },
    ],
  },
  {
    id: "strengths",
    title: "強み・特徴",
    description: "御社のアピールポイントをたくさん教えてください！",
    icon: "⭐",
    step: 1,
    estimatedMinutes: 10,
    fields: [
      {
        name: "strengths",
        label: "会社の強み・特徴",
        type: "repeater",
        placeholder: "強みを入力",
        hint: "直感的な言葉でOKです！説明はラフに書いてもらえればAIで整えますよ！",
        dnaSheet: "00_Company",
        dnaField: "strengths",
        defaultCount: 3,
        suggestions: [
          { title: "技術力", description: "長年培ってきた独自の技術力で、お客さまの課題を解決します。" },
          { title: "スピード対応", description: "お問い合わせから24時間以内にご回答。スピード感のある対応を徹底しています。" },
          { title: "ワンストップ対応", description: "企画から制作、運用まで一貫して対応。窓口が1つなのでスムーズです。" },
          { title: "実績・信頼", description: "創業以来〇年の実績。〇〇社以上のお客さまにご利用いただいています。" },
          { title: "柔軟なカスタマイズ", description: "お客さまのご要望に合わせて柔軟にカスタマイズ。「ちょうどいい」をご提案します。" },
          { title: "アフターサポート", description: "納品後もしっかりサポート。困ったときにすぐ相談できる体制を整えています。" },
        ],
      },
      {
        name: "differentiator",
        label: "他社との違い（最大の差別化ポイント）",
        type: "textarea",
        placeholder: "例：同業他社と比べて、当社は〇〇が圧倒的に違います",
        hint: "「ここだけは負けない！」というポイントを教えてください！",
        dnaSheet: "00_Company",
        dnaField: "differentiator",
      },
    ],
  },
  // ── ステップ2 ──────────────────────────────────────────
  {
    id: "origin-story",
    title: "創業ストーリー",
    description: "会社の成り立ちを教えてください！",
    icon: "🌱",
    step: 2,
    estimatedMinutes: 10,
    fields: [
      {
        name: "founding_reason",
        label: "創業のきっかけ",
        type: "textarea",
        placeholder: "自由にお書きください",
        hint: "なぜこの会社を作ったのか、その物語が一番のオリジナルコンテンツです！",
        dnaSheet: "03_Philosophy",
        dnaField: "origin",
        textSuggestions: [
          { label: "課題を感じた", text: "会社を立ち上げたきっかけは、" },
          { label: "転機があった", text: "人生の転機になったのは、" },
          { label: "出会いから", text: "ある出会いがきっかけでした。" },
        ],
      },
      {
        name: "company_name_origin",
        label: "社名・ロゴに込めた想い",
        type: "textarea",
        placeholder: "例：「〇〇」という社名には、〇〇という想いを込めています",
        hint: "世界に1つだけの物語！AIには絶対書けない最強の一次情報です！",
        dnaSheet: "03_Philosophy",
        dnaField: "name_origin",
      },
      {
        name: "hardest_moment",
        label: "一番大変だったこと",
        type: "textarea",
        placeholder: "例：創業2年目に〇〇という壁にぶつかりましたが、〇〇して乗り越えました",
        hint: "苦労話は共感と信頼を生みます！",
        dnaSheet: "03_Philosophy",
        dnaField: "hardest_moment",
      },
    ],
  },
  {
    id: "results",
    title: "実績・お客様の声",
    description: "これまでの実績やお客さまの声を教えてください！",
    icon: "📖",
    step: 2,
    estimatedMinutes: 10,
    fields: [
      {
        name: "achievements",
        label: "主な実績・数字",
        type: "textarea",
        placeholder: "例：\n・取引社数 300社以上\n・年間プロジェクト数 150件\n・リピート率 85%",
        hint: "具体的な数字があると説得力が格段に上がります！",
        dnaSheet: "00_Company",
        dnaField: "achievements",
        rows: 6,
      },
      {
        name: "client_voices",
        label: "お客様の声・推薦コメント",
        type: "repeater",
        placeholder: "お客様名（匿名可）",
        hint: "実際にいただいた言葉を教えてください！第三者の声は最強のコンテンツです！",
        dnaSheet: "00_Company",
        dnaField: "client_voices",
        defaultCount: 2,
      },
      {
        name: "case_studies",
        label: "導入事例・プロジェクト事例",
        type: "repeater",
        placeholder: "事例タイトル",
        hint: "「課題→解決策→成果」の形で書けるとベストです！",
        dnaSheet: "00_Company",
        dnaField: "case_studies",
        defaultCount: 2,
      },
    ],
  },
  {
    id: "team",
    title: "チーム・社風",
    description: "どんな会社か、雰囲気を教えてください！",
    icon: "👥",
    step: 2,
    estimatedMinutes: 10,
    fields: [
      {
        name: "culture",
        label: "社風・カルチャー",
        type: "textarea",
        placeholder: "例：フラットな組織で、年齢や役職に関係なく意見を言い合える環境です",
        hint: "採用にも直結する重要な情報です！",
        dnaSheet: "00_Company",
        dnaField: "culture",
      },
      {
        name: "team_message",
        label: "社員に一番伝えていること",
        type: "textarea",
        placeholder: "例：「お客さまの期待の一歩先を行こう」といつも言っています",
        hint: "チームの価値観が伝わります！",
        dnaSheet: "03_Philosophy",
        dnaField: "team_message",
      },
      {
        name: "other_staff",
        label: "メンバー紹介",
        type: "staff-repeater",
        hint: "主要メンバーの情報を追加できます！",
        dnaSheet: "10_Staff",
        dnaField: "name",
      },
      {
        name: "future_vision",
        label: "今後の展望",
        type: "textarea",
        placeholder: "例：5年後にはアジア展開を目指しています",
        hint: "将来のビジョンがあると「一緒に働きたい」「取引したい」と思ってもらえます！",
        dnaSheet: "03_Philosophy",
        dnaField: "future_vision",
      },
    ],
  },
  {
    id: "services",
    title: "サービス・事業詳細",
    description: "提供しているサービスの詳細を教えてください！",
    icon: "📋",
    step: 2,
    estimatedMinutes: 15,
    fields: [
      {
        name: "services",
        label: "サービス一覧",
        type: "repeater",
        placeholder: "サービス名",
        hint: "提供しているサービスを教えてください！それぞれの特徴も！",
        dnaSheet: "04_Services",
        dnaField: "content",
        defaultCount: 3,
      },
      {
        name: "service_flow",
        label: "ご利用の流れ",
        type: "textarea",
        placeholder: "例：\n1. お問い合わせ\n2. ヒアリング\n3. ご提案\n4. 制作・開発\n5. 納品\n6. アフターサポート",
        hint: "初めてのお客さま向けの流れです！",
        dnaSheet: "04_Services",
        dnaField: "flow",
        rows: 10,
        textSuggestions: [
          { label: "一般的な流れ", text: "1. お問い合わせ\nWebフォームまたはお電話でお気軽にご連絡ください。\n\n2. ヒアリング\nご要望や課題を詳しくお伺いします。\n\n3. ご提案・お見積り\n最適なプランをご提案いたします。\n\n4. 制作・実施\nご了承いただいた内容で進めます。\n\n5. 納品・報告\n成果物の納品と結果報告を行います。\n\n6. アフターサポート\n納品後もしっかりサポートいたします。" },
        ],
      },
      {
        name: "faq",
        label: "よくある質問",
        type: "repeater",
        placeholder: "質問",
        hint: "お客さまからよく聞かれることを教えてください！",
        dnaSheet: "04_Services",
        dnaField: "faq",
        defaultCount: 3,
      },
    ],
  },
];
